name: shuttlers_test
description: A technical assessment project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.1.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  nuts_activity_indicator: 
    git: 
      url: https://github.com/khulegu/nuts_and_bolts_nullsafety/
      path: packages/nuts_activity_indicator
  provider: ^5.0.0
  sliding_sheet: ^0.5.2
  swipeable_tile: ^1.0.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 